version: '2.1'
# define all services
services:
# our service is called CakePHP ;-)
  cakephp:
  # we want to use the image which is build from our Dockerfile
    build:
      context: .
      dockerfile: ./Dockerfile.cakephp
    # apache is running on port 80 but we want to expose this to port 4000 on our local machine
    ports:
      - "4000:80"
    # we are depending on the mysql backend
    extra_hosts:
        - "cakephp:192.168.99.100"
    hostname: cakephp    
    depends_on:
      - mysql
      # we mount the working dir into the container, handy for development
    volumes: 
      - .:/var/www/html/

    environment:
      - SECURITY_SALT
      - MYSQL_HOST=mysql
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=1234
  mysql:
    # we use the mysql base image, version 5.6.36
    image: mariadb:10.4.11
    ports:
      - "3030:3006" 
    # we mount a datavolume to make sure we don't lose data
    volumes:
      - /var/lib/mysql
    # setting some envvars to create the DB
    environment:
    - MYSQL_ROOT_PASSWORD=1234
    - MYSQL_DATABASE=test
volumes:
  mysql_data: