version: '2'
services:
    mysql:
        restart: always
        build: ./data/mysql/
        volumes:
            - "./data/mysql/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWOD: 1234
            MYSQL_USER: my_app
            MYSQL_PASSWORD: 1234
            MYSQL_DATABASE: test
        ports:
            - "3307:3306"
    nginx:
        restart: always
        image: "nginx:mainline-alpine"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./data/ngninx/conf:/etc/nginx/"
            - "./data/htdocs:/var/www/html"
        depends_on:
            - phpfpm
        links:
            - phpfpm
    phpfpm:
        restart: always
        build: ./data/phpfpm/
        volumes:
            - "./data/htdocs:/var/www/html"
        depends_on:
            - mysql
        links:
            - mysql
    host:
        build: ./data/htdocs
        environment:
            PRJ: "sample"
        volumes:
            - "./data/htdocs:/root"
        ports:
            - "8765:80"
        depends_on:
            - mysql
            - phpfpm
        links:
            - mysql
            - phpfpm